application: snipbin
version: 3
runtime: python
api_version: 1

handlers:
- url: /
  script: main.py
  
- url: /my
  script: main.py
  login: required
  
- url: /view
  script: view.py
  
- url: /inc
  script: view.py
  
- url: /helper
  script: view.py
  
- url: /test
  script: test/test.py
  login: admin
  
- url: /api/.*
  script: api.py
  
- url: /stylesheets
  static_dir: stylesheets
  
- url: /js
  static_dir: js
  
- url: /(.*\.(gif|png|jpg|ico|crx))
  static_files: static/\1
  upload: static/(.*\.(gif|png|jpg|ico|crx))  

- url: /(about|legal|extension|extwelcome|credits)
  script: plainhtml.py
  
- url: /extlogin
  script: plainhtml.py
  login: required